image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
#  - push

build_and_push:
  stage: build
  before_script:
    - docker login -u "$DOCKER_LOGIN_USERNAME" -p "$DOCKER_LOGIN_PASSWORD" YOUR_CLOUD_CONTAINER_REGISTRY_HOST
  script:
    - docker build -f Dockerfile -t YOUR_CLOUD_CONTAINER_REGISTRY_HOST/gin-wire-template:"$CI_COMMIT_TAG" .
    - docker push YOUR_CLOUD_CONTAINER_REGISTRY_HOST/gin-wire-template:"$CI_COMMIT_TAG"
  tags:
    - docker
  only:
    - /^v.*$/   # Match tags starting with 'v'
